---
- name: Reload postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded
  become: true

- name: Restart postgresql
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  become: true
